#!/bin/bash
# Complete Service Status - All Running Apps

echo "=================================================="
echo "🎉 TẤT CẢ SERVICES ĐANG CHẠY"
echo "=================================================="
echo ""
echo "✅ 4 STREAMLIT APPS + 1 API BACKEND"
echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│ 1. 📹 REALTIME SCANNER (MỚI NHẤT!) ⭐        │"
echo "│    Port: 8504                                   │"
echo "│    URL:  http://localhost:8504                  │"
echo "│    Tính năng:                                   │"
echo "│    - Quét liên tục real-time                    │"
echo "│    - Tự động dừng khi thấy mặt                  │"
echo "│    - Auto-capture + xử lý                       │"
echo "│    - 3 modes: Đăng ký/Nhận diện/Check-in       │"
echo "└─────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│ 2. 🎨 MODERN UI                                 │"
echo "│    Port: 8503                                   │"
echo "│    URL:  http://localhost:8503                  │"
echo "│    Tính năng:                                   │"
echo "│    - Design đẹp với gradient                    │"
echo "│    - 4 modes: Quick Demo/Đăng ký/Nhận diện/FAS │"
echo "│    - Manual capture                             │"
echo "│    - Rich visual feedback                       │"
echo "└─────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│ 3. 📱 ORIGINAL STREAMLIT UI                     │"
echo "│    Port: 8502                                   │"
echo "│    URL:  http://localhost:8502                  │"
echo "│    Tính năng:                                   │"
echo "│    - Basic UI                                   │"
echo "│    - Webcam/Upload/Recognize/History            │"
echo "└─────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│ 4. ⚡ QUICK PIPELINE (demo_pipeline.py)         │"
echo "│    - Logic gốc của realtime scanning            │"
echo "│    - Chạy độc lập nếu cần                       │"
echo "└─────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│ 5. 🔧 FASTAPI BACKEND                           │"
echo "│    Port: 8000                                   │"
echo "│    API:  http://localhost:8000                  │"
echo "│    Docs: http://localhost:8000/docs             │"
echo "│    Endpoints:                                   │"
echo "│    - /detect_face                               │"
echo "│    - /recognize_face                            │"
echo "│    - /add_face                                  │"
echo "│    - /anti_spoofing                             │"
echo "│    - /process_frame (pipeline)                  │"
echo "└─────────────────────────────────────────────────┘"
echo ""
echo "=================================================="
echo "🎯 KHUYẾN NGHỊ SỬ DỤNG"
echo "=================================================="
echo ""
echo "🌟 REALTIME SCANNER (8504) - BEST FOR:"
echo "   ✅ Kiosk tự động"
echo "   ✅ Đăng ký nhanh"
echo "   ✅ Check-in tự động"
echo "   ✅ Demo ấn tượng"
echo "   → http://localhost:8504"
echo ""
echo "🎨 MODERN UI (8503) - BEST FOR:"
echo "   ✅ Demo đầy đủ tính năng"
echo "   ✅ Testing anti-spoofing"
echo "   ✅ Quick demo pipeline"
echo "   ✅ Manual control"
echo "   → http://localhost:8503"
echo ""
echo "🔧 API DOCS (8000) - BEST FOR:"
echo "   ✅ Integration testing"
echo "   ✅ API development"
echo "   ✅ Direct API calls"
echo "   → http://localhost:8000/docs"
echo ""
echo "=================================================="
echo "📊 DATABASE STATUS"
echo "=================================================="
echo ""
echo "📁 Location: data/faces.db"
echo "👥 Users:    4 người đã đăng ký"
echo "   - Thanh (user01)"
echo "   - Khanhh (user02)"
echo "   - Thanh10 (user10)"
echo "   - Thanh14 (user14)"
echo ""
echo "=================================================="
echo "🚀 QUICK START"
echo "=================================================="
echo ""
echo "Mở browser và chọn 1 trong các URL:"
echo ""
echo "1. Realtime scanning → http://localhost:8504  ⭐"
echo "2. Modern UI        → http://localhost:8503"
echo "3. Original UI      → http://localhost:8502"
echo "4. API Docs         → http://localhost:8000/docs"
echo ""
echo "=================================================="
